### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by remicollet** [steinm/ps#3]
package states this extension is BSD

BSD terms:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

So, it is impossible (for downstream packager) to respect this term, as the license file is missing

**Comment by remicollet** [comment]
BTW, ps.c header says "This source file is subject to version 2.02 of the PHP license"

- please fix license consistency
- if you keep PHP License, please update to latest v3.0.1 (older mays have issues for some distributions)

**Comment by steinm** [comment]
fixed in commit 00af3e4

**Comment by remicollet** [comment]
Thanks, this allows me to add RPM packages to my repository

Available for Fedora / RHEL / CentOS and other clones
With PHP 7.0 to 8.1

https://blog.remirepo.net/pages/PECL-extensions-RPM-status

Announced to users on my twitter account
